model:
  name: UNet2d
  in_channels: 3
  out_channels: 3
  init_features: 64
  scale_factor: 4
data:
  name: OceanNPY
  data_path: /ai/gno/DATA/ns/ns_V1e-5_N1200_T20.mat
  sample_factor: 4
  shape:
  - 200
  - 148
  train_batchsize: 24
  eval_batchsize: 12
  train_ratio: 0.98
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: false
  subset_ratio: 0.1
  normalize: true
  normalizer_type: PGN
  num_workers: 2
  dataset_root: /data/Bohai_Sea/process_data
  dyn_vars:
  - Vx
  - Vy
  - Vz
  patch_size: 64
  auto_patch: true
  model_divisor: 16
train:
  random_seed: 42
  cuda: true
  device: 0
  epochs: 500
  patience: 10
  eval_freq: 50
  saving_best: true
  load_ckpt: false
  saving_ckpt: true
  ckpt_freq: 50
  ckpt_max: 3
  distribute: false
  distribute_mode: DDP
  device_ids:
  - 0
  seed: 42
  use_amp: true
  gradient_checkpointing: true
  ckpt_path: ''
optimize:
  optimizer: AdamW
  lr: 0.001
  weight_decay: 0.001
schedule:
  scheduler: StepLR
  step_size: 300
  gamma: 0.5
log:
  verbose: true
  log: true
  log_dir: /data1/user/lz/wave_movie/testouts/UNet2d
  wandb: false
  wandb_project: OceanSR-UNet2d
